# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ExamProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExamProject
  pod 'RxSwift', '~> 3.0.0'
  pod 'RxCocoa', '~> 3.0.0'
  pod 'Moya/RxSwift', '~> 8.0.0'
  pod 'SnapKit', '~> 3.0.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Timepiece', '~> 1.2.0'

  target 'ExamProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
